AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  CsvTransformTool

  Sample Boomi AI Agent Tool for CSV Transformations
  
Globals:
  Function:
    Timeout: 3

Resources:
  CsvTransformFilesS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "boomi-ai-agent-tools-csv-tools-files"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        IgnorePublicAcls: True
        BlockPublicPolicy: True
        RestrictPublicBuckets: True
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      LifecycleConfiguration:
        Rules:
          - Id: "ExpireOldFiles"
            Status: Enabled
            Prefix: "output/"
            ExpirationInDays: 7

  CsvTransformToolFunction:
    Type: AWS::Serverless::Function 
    Properties:
      FunctionName: "CsvTransformToolFunction"
      CodeUri: csv_transform_tool/
      Handler: app.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      FunctionUrlConfig:
        AuthType: NONE
      Layers:
        - arn:aws:lambda:us-east-1:336392948345:layer:AWSSDKPandas-Python310:23
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref CsvTransformFilesS3Bucket
        - S3WritePolicy:
            BucketName: !Ref CsvTransformFilesS3Bucket

Outputs:
  CsvTransformToolFunctionUrl:
    Description: "URL for CsvTransformToolFunction function"
    Value: !GetAtt CsvTransformToolFunctionUrl.FunctionUrl
  CsvTransformToolFunction:
    Description: "CsvTransformToolFunction Lambda Function ARN"
    Value: !GetAtt CsvTransformToolFunction.Arn
  CsvTransformToolFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt CsvTransformToolFunctionRole.Arn
